<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9ce9f9c7a8d6
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Errors;

class APIException extends \Exception
{
    public int $statusCode;

    public function __construct(string $message, int $statusCode, public string $body, public ?\Psr\Http\Message\ResponseInterface $rawResponse)
    {
        $this->message = $message;
        $code = $statusCode;
        $this->statusCode = $statusCode;
        parent::__construct($message, $code);
    }

    public function __toString(): string
    {
        return "$this->message: Status $this->statusCode $this->body";
    }

}
