<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d0fe96947e7
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Errors;

class ErrorEnvelopeThrowable extends \RuntimeException
{
    public function __construct(string $message, int $statusCode, public ErrorEnvelope $container)
    {
        parent::__construct($message, $statusCode);
    }
}
