<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e187e6bbc568
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Errors;

use Gando\Partner\Models\Components;
use Gando\Partner\Utils;

class ErrorEnvelope
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Components\Error::class)]
        public Components\Error $error,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        #[\Speakeasy\Serializer\Annotation\Exclude]
        public ?\Psr\Http\Message\ResponseInterface $rawResponse = null,
    ) {
    }

    public function toException(): ErrorEnvelopeThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ErrorEnvelopeThrowable($message, $code, $this);
    }
}
