<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b37a16c555af
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;

class Credentials
{
    /**
     * @param  array<string>|null  $scopes
     */
    public function __construct(public string $clientID, public string $clientSecret, public string $tokenURL, public ?array $scopes)
    {
    }
}
