<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2ba4c41dd54c
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;
use Psr\Http\Message\ResponseInterface;

class ErrorResponseContext
{
    public function __construct(public ?ResponseInterface $response, public ?\Throwable $e)
    {
    }
}
