<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 279c02d439a6
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;

use Gando\Partner\SDKConfiguration;

class HookContext
{
    /**
     * @param  ?array<string>  $oauth2Scopes
     * @param  ?\Closure(): ?mixed  $securitySource
     */
    public function __construct(public SDKConfiguration $config, public string $baseURL, public string $operationID, public ?array $oauth2Scopes, public ?\Closure $securitySource)
    {
    }
    /**
     * @param  array<mixed>  $args
     */
    public function __call(string $name, array $args): mixed
    {
        if ($name === 'securitySource') {
            return call_user_func_array($this->securitySource, $args);
        }

        return null;
    }
}
