<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc21f349b594
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;

use Brick\DateTime\LocalTime;

class Session
{
    /**
     * @param  array<string>  $scopes
     */
    public function __construct(public Credentials $credentials, public string $token, public array $scopes, public ?LocalTime $expiresAt = null)
    {
    }
}
