<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aad5e2b1d06f
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;

class TokenResponse
{
    public ?string $accessToken = null;
    public ?string $tokenType = null;
    public ?int $expiresIn = null;
}
