<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 116b7f0c0f0f
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Partner link status: `active` (operations allowed) or `revoked` (403 on deposits) */
enum AccountStatus: string
{
    case Active = 'active';
    case Revoked = 'revoked';
}
