<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4486866af8fa
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

class AccountsListRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Filter linked accounts: `active` (default, operable links), `revoked` (disconnected), or `all`.
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
        public ?AccountsListQueryParamStatus $status = null,
        /**
         * Page number (1-based)
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
        public ?int $page = 1,
        /**
         * Items per page (max 100)
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
        public ?int $limit = 20
    ) {
    }
}
