<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e3ed06b98d1
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** AccountsRevokeResponseBody - Link revoked */
class AccountsRevokeResponseBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\PartnerRevokeAccountResponse::class)]
        public PartnerRevokeAccountResponse $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true
    ) {
    }
}