<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cde024b08534
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Models\Components;
use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class ClientsCreateRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[SpeakeasyMetadata('request:mediaType=application/json')]
        public Components\ParticulierClient|Components\ProfessionnelClient $body,
        /**
         * Optional UUID v4 for request deduplication (24h). Same key + same body replays the cached response; same key + different body returns 409 `idempotency_key_conflict`.
         */
        #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
        public ?string $idempotencyKey = null,
    ) {
    }
}
