<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 069c8e33d4d0
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Type of client: particulier (individual) or professionnel (business) */
enum ClientsUpdateClientType: string
{
    case Particulier = 'particulier';
    case Professionnel = 'professionnel';
}
