<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 81478bd6ae5f
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** ClientsListResponseBody - Paginated clients */
final readonly class ClientsListResponseBody
{
    /**
     * @param  bool  $success
     * @param  \Gando\Partner\Models\Operations\V1ClientsListResponse  $data
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\V1ClientsListResponse::class)]
        public V1ClientsListResponse $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true,
    ) {}
}
