<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4bf37c74934
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** ClientsCreateResponseBody1 - Client already exists (idempotent create) */
class ClientsCreateResponseBody1
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\PartnerCreateClientResponse1::class)]
        public PartnerCreateClientResponse1 $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true
    ) {
    }
}