<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 663e6e75b8e3
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class ClientsCreateResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP response content type for this operation
         */
        public string $contentType,
        /**
         * HTTP response status code for this operation
         */
        public int $statusCode,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public \Psr\Http\Message\ResponseInterface $rawResponse,
        /**
         * Client already exists (idempotent create)
         */
        public ?ClientsCreateResponseBody1 $twoHundredApplicationJsonObject = null,
        /**
         * Client created
         */
        public ?ClientsCreateResponseBody2 $twoHundredAndOneApplicationJsonObject = null
    ) {
    }
}