<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9d8ac4ebf2e7
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Models\Components;
use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class ClientsUpdateRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Client unique identifier
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
        #[SpeakeasyMetadata('request:mediaType=application/json')]
        public Components\ParticulierPartnerClientPatch|Components\ProfessionnelPartnerClientPatch $body,
    ) {
    }
}
