<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d210158178d4
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class CreatePartnerWebhookSubscriptionBody
{
    /**
     * @param  ?array<\Gando\Partner\Models\Operations\WebhooksCreateEventRequest>  $events
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Destination URL (must start with http:// or https://)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
        public string $url,
        /**
         * Event types to subscribe. Defaults to all partner events when omitted.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksCreateEventRequest>|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?array $events = null,
    ) {
    }
}
