<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class Data
{
    /**
     * Per-recipient send results
     *
     * @var array<\Gando\Partner\Models\Operations\Result> $results
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\Result>')]
    public array $results;

    /**
     * @param  array<\Gando\Partner\Models\Operations\Result>  $results
     * @phpstan-pure
     */
    public function __construct(array $results)
    {
        $this->results = $results;
    }
}