<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f04080e6944
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class DepositsCaptureRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposit (caution) unique identifier
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
        #[SpeakeasyMetadata('request:mediaType=application/json')]
        public PartnerCaptureBody $body,
        /**
         * Optional UUID v4 for request deduplication (24h). Same key + same body replays the cached response; same key + different body returns 409 `idempotency_key_conflict`.
         */
        #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
        public ?string $idempotencyKey = null,
    ) {
    }
}
