<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd5511013e99
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class DepositsUpdatePartnerDepositMutationOk
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Operation completed successfully
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true,
    ) {
    }
}
