<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9bfc5cf8fec6
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** DepositsCancelResponseBody - Closed */
class DepositsCancelResponseBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\DepositsCancelPartnerDepositMutationOk::class)]
        public DepositsCancelPartnerDepositMutationOk $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true
    ) {
    }
}