<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 696f7b0d6a9d
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** DepositsGetPaymentMethodResponseBody - Masked PAN / brand */
class DepositsGetPaymentMethodResponseBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\PartnerPaymentMethodInfo::class)]
        public PartnerPaymentMethodInfo $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true
    ) {
    }
}