<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d2d8b4666e1
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class DepositsGetCaptureResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP response content type for this operation
         */
        public string $contentType,
        /**
         * HTTP response status code for this operation
         */
        public int $statusCode,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public \Psr\Http\Message\ResponseInterface $rawResponse,
        /**
         * Capture summary
         */
        public ?DepositsGetCaptureResponseBody $object = null
    ) {
    }
}