<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 44455e02bd23
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class DepositsSendDepositMailResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP response content type for this operation
         */
        public string $contentType,
        /**
         * HTTP response status code for this operation
         */
        public int $statusCode,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public \Psr\Http\Message\ResponseInterface $rawResponse,
        /**
         * Send result
         */
        public ?DepositsSendDepositMailResponseBody $object = null,
    ) {
    }
}
