<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0b6f507e20aa
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class DepositsListResponse
{
    /**
     * @var \Closure(string): ?DepositsListResponse $next
     */
    public \Closure $next;
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP response content type for this operation
         */
        public string $contentType,
        /**
         * HTTP response status code for this operation
         */
        public int $statusCode,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public \Psr\Http\Message\ResponseInterface $rawResponse,
        /**
         * Paginated list (`items` + `total` + `numPages`; optional `counts`)
         */
        public ?DepositsListResponseBody $object = null
    ) {
    }
    /**
     * @param  array<mixed>  $args
     */
    public function __call(string $name, array $args): ?DepositsListResponse
    {
        if ($name === 'next') {
            return call_user_func_array($this->next, $args);
        }

        return null;
    }
}