<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cec8f342afe2
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;
class DepositsDeleteRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposit (caution) unique identifier
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id
    ) {
    }
}