<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 56c5a53b9056
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class DepositsSendEmailsRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposit (caution) unique identifier
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
        #[SpeakeasyMetadata('request:mediaType=application/json')]
        public PartnerDepositEmailsBody $body,
    ) {
    }
}
