<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 726370aa95dd
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Currency code (always EUR) */
enum DepositsListCurrency: string
{
    case Eur = 'EUR';
}
