<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 800296be229d
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Event type delivered */
enum EventType: string
{
    case DepositStatusChanged = 'deposit.status_changed';
    case DepositActivated = 'deposit.activated';
    case DepositCaptured = 'deposit.captured';
    case DepositExpired = 'deposit.expired';
    case DepositCancelled = 'deposit.cancelled';
    case RentalOperatorLinked = 'rental_operator.linked';
}
