<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cfe7abf11558
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class Item
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Unique identifier of the caution
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
        /**
         * Unique reference code for the caution
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
        public string $reference,
        /**
         * Amount of the caution in euros
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
        public float $amount,
        /**
         * Currency code (always EUR)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\DepositsListCurrency::class)]
        public DepositsListCurrency $currency,
        /**
         * Status of the caution: pending (waiting for next step), incomplete (client journey not finished), active (payment authorized), processing (being processed), captured (payment captured), close (caution closed by natural expiration / end of contract), cancelled (caution cancelled manually before activation or while active), payment_issue (payment issue at fee payment), capture_issue (capture/recovery issue)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\StatusEur::class)]
        public StatusEur $status,
        /**
         * Creation date and time (ISO 8601 format)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
        public \DateTime $createdAt,
        /**
         * Last update date and time (ISO 8601 format)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
        public \DateTime $updatedAt,
        /**
         * Rental contract reference
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('rentalContract')]
        public ?string $rentalContract = null,
        /**
         * Contract start date (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('contractStartAt')]
        public ?\DateTime $contractStartAt = null,
        /**
         * Contract end date (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('contractEndAt')]
        public ?\DateTime $contractEndAt = null,
        /**
         * ID of the client associated with the caution (optional, can be null)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('clientId')]
        public ?string $clientId = null,
        /**
         * Whether the caution is archived (soft-deleted)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('isArchived')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?bool $isArchived = null,
        /**
         * ID of the account that owns the caution
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('accountId')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $accountId = null,
        /**
         * Payment processor reference for the deposit authorisation (when present)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('stripePaymentIntentId')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $stripePaymentIntentId = null,
        /**
         * Payment processor reference for the saved card on the caution (when present)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('stripePaymentMethodId')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $stripePaymentMethodId = null,
        /**
         * Start date and time of the caution (ISO 8601 format)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('startAt')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?\DateTime $startAt = null,
        /**
         * Expiration date and time of the caution (ISO 8601 format)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('expiresAt')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?\DateTime $expiresAt = null
    ) {
    }
}