<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d836f3222308
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Pagination - Pagination metadata */
final readonly class Pagination
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Current page number
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('page')]
        public float $page,
        /**
         * Number of items per page
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('limit')]
        public float $limit,
        /**
         * Total number of items
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
        public float $total,
        /**
         * Total number of pages
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('totalPages')]
        public float $totalPages,
    ) {
    }
}
