<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2a255529d9c5
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerClientsListResponse
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\ClientsListPartnerClientItem>  $items
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Clients for the current page
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\ClientsListPartnerClientItem>')]
        public array $items,
        /**
         * Pagination metadata
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\Pagination::class)]
        public Pagination $pagination
    ) {
    }
}