<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aea9f323656a
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class PartnerWebhookRotateSecretResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * New plain signing secret. Store securely; shown once per rotation.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
        public string $secret,
    ) {
    }
}
