<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 69d5c9a35940
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerCaptureInfo
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Capture amount in EUR cents
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('amountCents')]
        public int $amountCents,
        /**
         * Gando collection fee in EUR cents
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('feeCents')]
        public int $feeCents,
        /**
         * Net amount credited to the rental operator in EUR cents
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('netCents')]
        public int $netCents,
        /**
         * Capture status (e.g. paid, pending, failed)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        public string $status,
        /**
         * Capture reason if provided
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
        public ?string $reason = null,
    ) {
    }
}
