<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dae37bf3a301
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerSendDepositMailBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Single recipient for the deposit completion link
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
        public string $email,
    ) {
    }
}
