<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 93baa7de9ca9
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class PartnerDepositListResponse
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\Item>  $items
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposits for the current page
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\Item>')]
        public array $items,
        /**
         * Total deposits matching filters
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
        public int $total,
        /**
         * Total number of pages for the current `limit` (0 when `total` is 0)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('numPages')]
        public int $numPages,
        /**
         * Present only when `include_counts=true` and `account_id` is set
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('counts')]
        #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\PartnerDepositListCounts|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?PartnerDepositListCounts $counts = null,
    ) {
    }
}
