<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4b6a46a1a4b2
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** PartnerDeleteDepositResponse - Deleted or archived */
class PartnerDeleteDepositResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * `Deleted` when removed; `Archived` when soft-deleted instead
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\Message::class)]
        public Message $message,
        /**
         * Always true on success
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true,
    ) {
    }
}
