<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a995b0af2e99
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerWebhookDeliveryItem
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Webhook delivery unique identifier
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
        /**
         * Event type delivered
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('eventType')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\EventType::class)]
        public EventType $eventType,
        /**
         * Delivery attempt number (1-based)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('attemptCount')]
        public int $attemptCount,
        /**
         * Delivery record creation timestamp (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
        public \DateTime $createdAt,
        /**
         * HTTP status code returned by your endpoint
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
        public ?int $statusCode = null,
        /**
         * Error message when delivery failed
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
        public ?string $error = null,
        /**
         * ISO 8601 timestamp when delivery succeeded
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('deliveredAt')]
        public ?\DateTime $deliveredAt = null,
        /**
         * ISO 8601 timestamp of the next retry, if scheduled
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('nextRetryAt')]
        public ?\DateTime $nextRetryAt = null,
    ) {
    }
}
