<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: be4692d1536c
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerWebhookTestOk
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP status code returned by your webhook URL
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
        public int $statusCode
    ) {
    }
}