<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c9c213462e87
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerPatchDepositBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Reassign deposit to another client on the same rental operator account
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('client_id')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $clientId = null,
        /**
         * Void the in-flight deposit payment and set status to `cancelled` (not the same as POST …/cancel which closes an active deposit)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('action')]
        #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\Action|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?Action $action = null
    ) {
    }
}