<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 379ed1fe7d88
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class PartnerSendDepositMailResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposit completion URL
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
        public string $link,
        /**
         * Whether the email was accepted by the provider
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success,
        /**
         * Transactional email provider message id, when available
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('messageId')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $messageId = null,
    ) {
    }
}
