<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ddec8bb0637b
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerDepositEmailsBody
{
    /**
     * @param  array<string>  $emails
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Recipient email addresses for the deposit completion link
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('emails')]
        #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
        public array $emails,
    ) {
    }
}
