<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f92bc6ac00b
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerAccountList
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\PartnerLinkedAccount>  $accounts
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Linked rental operator accounts for this partner
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('accounts')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\PartnerLinkedAccount>')]
        public array $accounts,
        /**
         * Total number of accounts matching the filter
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
        public int $total
    ) {
    }
}