<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 76c534ce94bb
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class PartnerRevokeAccountResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Link status after revocation
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\AccountsRevokeStatus::class)]
        public AccountsRevokeStatus $status,
        /**
         * ISO 8601 timestamp when the link was revoked
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('revokedAt')]
        public \DateTime $revokedAt,
    ) {
    }
}
