<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6aab002b8843
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerCaptureResult
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Captured amount in EUR cents
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('capturedAmount')]
        public int $capturedAmount,
        /**
         * Capture outcome status from the payment processor
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        public string $status,
    ) {
    }
}
