<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a03760bf1dfa
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerWebhookListResponse
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\WebhooksListPartnerWebhookSubscriptionItem>  $items
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Webhook endpoints for the current page
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksListPartnerWebhookSubscriptionItem>')]
        public array $items,
        /**
         * Total webhook endpoints for this partner
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
        public int $total
    ) {
    }
}