<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85981c494d6f
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerDeleteWebhookResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Webhook endpoint was removed
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('deleted')]
        public bool $deleted = true
    ) {
    }
}