<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e13102639823
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerCreateDepositResponse
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Deposit unique identifier
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
        /**
         * Human-readable deposit reference (e.g. GAN-XXXX)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
        public string $reference,
        /**
         * Status of the caution: pending (waiting for next step), incomplete (client journey not finished), active (payment authorized), processing (being processed), captured (payment captured), close (caution closed by natural expiration / end of contract), cancelled (caution cancelled manually before activation or while active), payment_issue (payment issue at fee payment), capture_issue (capture/recovery issue)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\DepositsCreateStatus::class)]
        public DepositsCreateStatus $status,
        /**
         * Deposit amount in euros
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
        public float $amount,
        /**
         * Creation timestamp (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
        public \DateTime $createdAt,
        /**
         * Tenant checkout URL when `inline_redirect` was true on create
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_url')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $depositUrl = null
    ) {
    }
}