<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16ff57a4f33c
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerLinkedAccount
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Gando rental operator account id. Use as `account_id` in Partner API calls.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('accountId')]
        public string $accountId,
        /**
         * ISO 8601 timestamp when the partner link was created
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('linkedAt')]
        public \DateTime $linkedAt,
        /**
         * Partner link status: `active` (operations allowed) or `revoked` (403 on deposits)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\AccountStatus::class)]
        public AccountStatus $status,
        /**
         * Your external id from partner connect, when provided at link time
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
        public ?string $externalId = null,
        /**
         * Legal or trade name of the rental operator
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
        public ?string $companyName = null,
        /**
         * Display name in Gando dashboards
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('displayName')]
        public ?string $displayName = null,
        /**
         * Primary contact email for the rental operator
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
        public ?string $email = null,
    ) {
    }
}
