<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerDepositScoring
{
    /**
     * Bridge solvency score when available
     *
     * @var ?float $score
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('score')]
    public ?float $score;

    /**
     * Risk rating (e.g. low, normal, sensitive, high)
     *
     * @var ?string $rating
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rating')]
    public ?string $rating;

    /**
     * @param  ?float  $score
     * @param  ?string  $rating
     * @phpstan-pure
     */
    public function __construct(?float $score = null, ?string $rating = null)
    {
        $this->score = $score;
        $this->rating = $rating;
    }
}