<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 87cc0f4a8f21
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** PartnerDepositListCounts - Present only when `include_counts=true` and `account_id` is set */
final readonly class PartnerDepositListCounts
{
    /**
     * @param  array<string, int>  $byStatus
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Total deposits for the filtered account
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
        public int $total,
        /**
         * Deposit count keyed by status
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('byStatus')]
        #[\Speakeasy\Serializer\Annotation\Type('array<string, int>')]
        public array $byStatus,
    ) {
    }
}
