<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0bee8169e741
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerWebhookSubscriptionCreated
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\WebhooksCreateEventResponse>  $events
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Partner webhook endpoint id (use as `{id}` in follow-up routes)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
        /**
         * Destination URL for webhook deliveries
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
        public string $url,
        /**
         * Subscribed event list
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksCreateEventResponse>')]
        public array $events,
        /**
         * Creation date and time (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
        public \DateTime $createdAt,
        /**
         * Plain signing secret. Returned only once at creation (store it securely).
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
        public string $secret,
    ) {
    }
}
