<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9f1fb72e7571
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class PartnerCreateClientResponse2
{
    /**
     * Created or existing client id (use as `clientId` on deposits)
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Created or existing client id (use as `client_id` on deposits)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
    ) {
    }
}
