<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe76cf45b6ba
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Field to sort deposit results by */
enum SortBy: string
{
    case Amount = 'amount';
    case Status = 'status';
    case RentalContract = 'rentalContract';
    case StartAt = 'startAt';
    case ExpiresAt = 'expiresAt';
    case Reference = 'reference';
    case CreatedAt = 'createdAt';
}
