<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 087bfb13844e
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** UpdatePartnerWebhookSubscriptionBody - Partner webhook endpoint update payload */
class UpdatePartnerWebhookSubscriptionBody
{
    /**
     * @param  ?array<\Gando\Partner\Models\Operations\WebhooksUpdateEventRequest>  $events
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Destination URL (must start with http:// or https://)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $url = null,
        /**
         * Replace the subscribed event list
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksUpdateEventRequest>|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?array $events = null,
        /**
         * Enable or disable deliveries for this endpoint
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('isActive')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?bool $isActive = null
    ) {
    }
}