<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class V1DepositListResponse
{
    /**
     * Deposits for the current page
     *
     * @var array<\Gando\Partner\Models\Operations\DepositsListDepositItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\DepositsListDepositItem>')]
    public array $items;

    /**
     * Total deposits matching filters
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     * Total number of pages for the current `limit` (0 when `total` is 0)
     *
     * @var int $numPages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('numPages')]
    public int $numPages;

    /**
     * Present only when `includeCounts=true` and `accountId` query is set
     *
     * @var ?\Gando\Partner\Models\Operations\V1DepositListCounts $counts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('counts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\V1DepositListCounts|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V1DepositListCounts $counts = null;

    /**
     * @param  array<\Gando\Partner\Models\Operations\DepositsListDepositItem>  $items
     * @param  int  $total
     * @param  int  $numPages
     * @param  ?\Gando\Partner\Models\Operations\V1DepositListCounts  $counts
     * @phpstan-pure
     */
    public function __construct(array $items, int $total, int $numPages, ?V1DepositListCounts $counts = null)
    {
        $this->items = $items;
        $this->total = $total;
        $this->numPages = $numPages;
        $this->counts = $counts;
    }
}