<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a48df3854f1
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class V1WebhookListResponse
{
    /**
     * Webhook endpoints for the current page
     *
     * @var array<\Gando\Partner\Models\Operations\WebhooksListV1WebhookSubscriptionItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksListV1WebhookSubscriptionItem>')]
    public array $items;

    /**
     * Total webhook endpoints for this partner
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     * @param  array<\Gando\Partner\Models\Operations\WebhooksListV1WebhookSubscriptionItem>  $items
     * @param  int  $total
     * @phpstan-pure
     */
    public function __construct(array $items, int $total)
    {
        $this->items = $items;
        $this->total = $total;
    }
}