<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96fdfbb78f48
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class WebhooksUpdateRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Partner webhook endpoint id
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
        /**
         * Partner webhook endpoint update payload
         */
        #[SpeakeasyMetadata('request:mediaType=application/json')]
        public UpdatePartnerWebhookSubscriptionBody $body,
    ) {
    }
}
