<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d9bdde0a5cc
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

class WebhooksListResponse
{
    /**
     * @var \Closure(string): ?WebhooksListResponse $next
     */
    public \Closure $next;
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * HTTP response content type for this operation
         */
        public string $contentType,
        /**
         * HTTP response status code for this operation
         */
        public int $statusCode,
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public \Psr\Http\Message\ResponseInterface $rawResponse,
        /**
         * Paginated webhook endpoints (`items` + `total`)
         */
        public ?WebhooksListResponseBody $object = null,
    ) {
    }
    /**
     * @param  array<mixed>  $args
     */
    public function __call(string $name, array $args): ?WebhooksListResponse
    {
        if ($name === 'next') {
            return call_user_func_array($this->next, $args);
        }

        return null;
    }
}
