<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2de8f3a9e6c4
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;
class WebhooksGetDeliveriesRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Partner webhook endpoint id
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
        /**
         * Page size (1–100, default 20)
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
        public ?int $limit = null,
        /**
         * Number of deliveries to skip
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
        public ?int $offset = null
    ) {
    }
}