<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4f6f05acf99d
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** Partner webhook event types. `rental_operator.linked` fires when a rental operator account is linked to your partner via connect. The five deposit events mirror rental-operator webhooks: `deposit.status_changed` is the wildcard delivered for every status transition; `deposit.activated` (-> active), `deposit.captured` (-> captured), `deposit.expired` (-> close, natural end of contract), `deposit.cancelled` (-> cancelled, manual cancellation) are the specific events. When an endpoint subscribes to both the wildcard and a specific event, the most specific subscribed event wins for that transition (single delivery per endpoint). */
enum WebhooksUpdateEventRequest: string
{
    case RentalOperatorLinked = 'rental_operator.linked';
    case DepositStatusChanged = 'deposit.status_changed';
    case DepositActivated = 'deposit.activated';
    case DepositCaptured = 'deposit.captured';
    case DepositExpired = 'deposit.expired';
    case DepositCancelled = 'deposit.cancelled';
}
