<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d9bdde0a5cc
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class WebhooksListResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Paginated webhook endpoints (`items` + `total`)
     *
     * @var ?\Gando\Partner\Models\Operations\WebhooksListResponseBody $object
     */
    public ?WebhooksListResponseBody $object = null;

    /**
     * @var \Closure(string): ?WebhooksListResponse $next
     */
    public \Closure $next;
    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  ?\Gando\Partner\Models\Operations\WebhooksListResponseBody  $object
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, ?WebhooksListResponseBody $object = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->object = $object;
    }
    /**
     * @param  string  $name
     * @param  array<mixed>  $args
     * @return ?WebhooksListResponse
     */
    public function __call($name, $args): ?WebhooksListResponse
    {
        if ($name === 'next') {
            return call_user_func_array($this->next, $args);
        }

        return null;
    }
}