<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 092be43316bc
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** WebhooksUpdateResponseBody - Updated */
final readonly class WebhooksUpdateResponseBody
{
    /**
     * @param  bool  $success
     * @param  \Gando\Partner\Models\Operations\WebhooksUpdateV1WebhookSubscriptionItem  $data
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\WebhooksUpdateV1WebhookSubscriptionItem::class)]
        public WebhooksUpdateV1WebhookSubscriptionItem $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true,
    ) {
    }
}
