<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: adfc8db69465
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

/** WebhooksListResponseBody - Paginated webhook endpoints (`items` + `total`) */
final readonly class WebhooksListResponseBody
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Operations\PartnerWebhookListResponse::class)]
        public PartnerWebhookListResponse $data,
        /**
         * Optional human-readable message
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $message = null,
        /**
         * Always `true` for successful responses
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
        public bool $success = true,
    ) {
    }
}
