<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** V1 webhook event types. `deposit.status_changed` is the wildcard delivered for every status transition. `deposit.activated` (-> active), `deposit.captured` (-> captured), `deposit.expired` (-> close), `deposit.cancelled` (-> cancelled) are specific events. `rental_operator.linked` fires when a rental operator account is linked to your partner via connect. When a subscription includes both the wildcard and a specific event, the most specific subscribed event wins for that transition (single delivery per endpoint). */
enum WebhooksUpdateEventResponse: string
{
    case DepositStatusChanged = 'deposit.status_changed';
    case DepositActivated = 'deposit.activated';
    case DepositCaptured = 'deposit.captured';
    case DepositExpired = 'deposit.expired';
    case DepositCancelled = 'deposit.cancelled';
    case RentalOperatorLinked = 'rental_operator.linked';
}
