<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e8990da4c862
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class WebhooksTestRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Partner webhook endpoint id
         */
        #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
        public string $id,
    ) {
    }
}
