<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98cec1542ed5
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class WebhooksListRequest
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Page number (1-based)
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
        public ?int $page = 1,
        /**
         * Items per page (max 100)
         */
        #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
        public ?int $limit = 20,
    ) {
    }
}
