<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c80ecd86f625
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

final readonly class WebhooksUpdatePartnerWebhookSubscriptionItem
{
    /**
     * @param  array<\Gando\Partner\Models\Operations\WebhooksUpdateEventResponse>  $events
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Partner webhook endpoint id; path parameter `{id}` in update/delete/test/deliveries routes
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
        public string $id,
        /**
         * Destination URL for webhook deliveries
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
        public string $url,
        /**
         * Subscribed event types for this endpoint
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
        #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\WebhooksUpdateEventResponse>')]
        public array $events,
        /**
         * Whether this endpoint receives deliveries
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('isActive')]
        public bool $isActive,
        /**
         * Creation timestamp (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
        public \DateTime $createdAt,
        /**
         * Last update timestamp (ISO 8601)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
        public \DateTime $updatedAt,
    ) {
    }
}
