<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98710f1dd715
 */

declare(strict_types=1);

namespace Gando\Partner\Utils;

use ReflectionProperty;

class Headers
{
    /**
     * @param  array<string,array<string,array<string,string>>>|null  $globals
     * @return array<string,string>
     */
    public function parseHeaders(mixed $headers, ?array $globals = null): array
    {
        $out = [];

        if ($headers === null) {
            return $out;
        }

        foreach ($headers as $field => $value) {
            if ($globals !== null) {
                $value = populateGlobal($value, 'header', $field, $globals);
            }

            if ($value === null) {
                continue;
            }

            $metadata = $this->parseHeaderMetadata(new ReflectionProperty($headers::class, $field));
            if (!$metadata instanceof \Gando\Partner\Utils\ParamsMetadata) {
                continue;
            }

            $value = $this->serializeHeader($metadata, $value);
            if ($value === '') {
                continue;
            }
            if ($value === '0') {
                continue;
            }

            $out[$metadata->name] = $value;
        }

        return $out;
    }

    private function serializeHeader(ParamsMetadata $metadata, mixed $value): string
    {
        switch (gettype($value)) {
            case 'object':
                $items = [];

                foreach ($value as $field => $fieldValue) { /** @phpstan-ignore-line */
                    if ($fieldValue === null) {
                        continue;
                    }

                    $fieldMetadata = $this->parseHeaderMetadata(new ReflectionProperty($value::class, $field));
                    if (!$fieldMetadata instanceof \Gando\Partner\Utils\ParamsMetadata) {
                        continue;
                    }
                    if ($fieldMetadata->name === '') {
                        continue;
                    }
                    if ($fieldMetadata->name === '0') {
                        continue;
                    }

                    if ($metadata->explode) {
                        $items[] = $fieldMetadata->name.'='.valToString($fieldValue, ['dateTimeFormat' => $fieldMetadata->dateTimeFormat]);
                    } else {
                        $items[] = $fieldMetadata->name;
                        $items[] = valToString($fieldValue, ['dateTimeFormat' => $fieldMetadata->dateTimeFormat]);
                    }
                }

                return implode(',', $items);
            case 'array':
                if (array_is_list($value)) {
                    return implode(',', array_map(fn ($v): string => valToString($v, []), $value));
                }
                $items = [];
                foreach ($value as $field => $fieldValue) {
                    if ($fieldValue === null) {
                        continue;
                    }

                    if ($metadata->explode) {
                        $items[] = $field.'='.valToString($fieldValue, []);
                    } else {
                        $items[] = $field;
                        $items[] = valToString($fieldValue, []);
                    }
                }
                return implode(',', $items);
            default:
                return valToString($value, []);
        }
    }

    private function parseHeaderMetadata(ReflectionProperty $property): ?ParamsMetadata
    {
        $metadataStr = SpeakeasyMetadata::find($property->getAttributes(SpeakeasyMetadata::class), 'header');
        if ($metadataStr === null) {
            return null;
        }

        return ParamsMetadata::parse($metadataStr);
    }
}
