<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c675c18e8d43
 */

declare(strict_types=1);

namespace Gando\Partner\Utils;

use Gando\Partner\Utils\Retry\RetryConfig;

class Options
{
    public ?RetryConfig $retryConfig = null;

    /**
     * @var array<string>|null $retryCodes
     */
    public ?array $retryCodes = null;

    public static function builder(): OptionsBuilder
    {
        return new OptionsBuilder();
    }
}

class OptionsBuilder
{
    public Options $options;

    public function __construct()
    {
        $this->options = new Options();
    }

    /**
     * Sets the configuration to use for retries.
     */
    public function setRetryConfig(RetryConfig $config): OptionsBuilder
    {
        $this->options->retryConfig = $config;

        return $this;
    }

    /**
     * Specifies which HTTP status codes should be retried.
     *
     * @param  array<string>  $codes
     */
    public function setRetryCodes(array $codes): OptionsBuilder
    {
        $this->options->retryCodes = $codes;

        return $this;
    }

    public function build(): Options
    {
        return $this->options;
    }
}
