<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2b60c7b364fb
 */

declare(strict_types=1);

namespace Gando\Partner\Utils;

use phpDocumentor\Reflection\Type;
use Speakeasy\Serializer\Type\ParserInterface;

/**
 * Class PhpDocTypeParser
 *
 * This class translates from types in the formats supported byphpDocumentor
 * to the nested array format used by JMS/serializer.
 * 
 */
class PhpDocTypeParser implements ParserInterface
{

    private readonly \phpDocumentor\Reflection\TypeResolver $typeResolver;
    public function __construct()
    {
        $this->typeResolver = new \phpDocumentor\Reflection\TypeResolver();
    }

    /**
     * @return array<string, mixed>
     */
    public function parse(string $typeString): array
    {
        $type = $this->typeResolver->resolve($typeString);

        return $this->convertRecursive($type);
    }

    /**
     * @return array<string, mixed>
     */
    public function convertRecursive(Type $type): array
    {
        if ($type instanceof \phpDocumentor\Reflection\Types\AggregatedType) {
            return [
                'name' => 'union',
                'params' => \array_map($this->convertRecursive(...), iterator_to_array($type->getIterator())),
            ];
        }
        if ($type instanceof \phpDocumentor\Reflection\Types\Array_) {
            $params = [];
            $keyType = $type->getKeyType();
            if ($keyType instanceof \phpDocumentor\Reflection\Types\AggregatedType) {
                // The Default key that the phpdoc type system returns for *maps* is string|int, so if we see that, exclude it (which is the JMS/Serializer default).
                if (! ($keyType->getIterator()->count() === 2 && $keyType->contains(new \phpDocumentor\Reflection\Types\String_()) && $keyType->contains(new \phpDocumentor\Reflection\Types\Integer()))) {
                    $params[] = $this->convertRecursive($keyType);
                }
            } else {
                $params[] = $this->convertRecursive($keyType);
            }
            $valueType = $type->getValueType();
            $params[] = $this->convertRecursive($valueType);
            return [
                'name' => 'array',
                'params' => $params,
            ];
        }
        if ($type instanceof \phpDocumentor\Reflection\Types\Object_) {
            $className = $type->__toString();
            if (class_exists($className)) {
                $objectClass = new \ReflectionClass($className);
                if ($objectClass->isEnum()) {
                    return [
                        'name' => 'enum',
                        'params' => [
                            [
                                'name' => $objectClass->getName(),
                                'params' => [],
                            ],
                        ],
                    ];
                }
            }
        } elseif ($type instanceof \phpDocumentor\Reflection\Types\Null_) {
            return [
                'name' => 'NULL',
                'params' => [],
            ];
        }


        return [
            'name' => $type->__toString(),
            'params' => [],
        ];
    }
}