<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 30dc93a697d3
 */

declare(strict_types=1);

namespace Gando\Partner\Utils;

use ReflectionProperty;

class RequestBodies
{
    public const SERIALIZATION_METHOD_TO_CONTENT_TYPE = [
        'json' => 'application/json',
        'form' => 'application/x-www-form-urlencoded',
        'multipart' => 'multipart/form-data',
        'raw' => 'application/octet-stream',
        'string' => 'text/plain',
    ];

    /**
     * @return ?array<string,mixed>
     */
    public function serializeRequestBody(mixed $request, string $requestFieldName, string $serializationMethod): ?array
    {
        if ($request === null) {
            return null;
        }

        if (gettype($request) !== 'object' || ! property_exists($request, $requestFieldName)) {
            return $this->serializeContentType($requestFieldName, RequestBodies::SERIALIZATION_METHOD_TO_CONTENT_TYPE[$serializationMethod], $request);
        }

        $requestVal = $request->{$requestFieldName};
        if ($requestVal === null) {
            return null;
        }

        $metadata = RequestBodies::parseRequestMetadata(new ReflectionProperty($request::class, $requestFieldName));
        if (!$metadata instanceof \Gando\Partner\Utils\RequestMetadata) {
            throw new \Exception("Missing request metadata for field $requestFieldName");
        }

        return $this->serializeContentType($requestFieldName, $metadata->mediaType, $requestVal);
    }

    /**
     * @return ?array<string,mixed>
     */
    private function serializeContentType(string $fieldName, string $mediaType, mixed $value): ?array
    {
        if ($value === null) {
            return null;
        }

        $options = [];

        if (preg_match('/^(application|text)\/([^+]+\+)*json.*/', $mediaType)) {
            $serializer = JSON::createSerializer();
            $options['body'] = $serializer->serialize($value, 'json');
            $options['headers']['content-type'] = $mediaType;
        } elseif (preg_match('/multipart\/.*/', $mediaType)) {
            return $this->serializeMultipart($value);
        } elseif (preg_match('/application\/x-www-form-urlencoded.*/', $mediaType)) {
            return $this->serializeFormData($fieldName, $value);
        } else {
            $options['headers']['content-type'] = $mediaType;
            $type = gettype($value);

            match ($type) {
                'string' => $options['body'] = $value,
                default => throw new \RuntimeException("Invalid request body type $type for field $fieldName")
            };
        }

        return $options;
    }

    /**
     * @return array<string,mixed>
     */
    private function serializeMultipart(mixed $value): array
    {
        $options = [
            'multipart' => [],
        ];

        foreach ($value as $field => $val) {
            if ($val === null) {
                continue;
            }

            $metadata = $this->parseMultipartMetadata(new ReflectionProperty($value::class, $field));
            if (!$metadata instanceof \Gando\Partner\Utils\MultipartMetadata) {
                continue;
            }

            if ($metadata->file) {
                if (gettype($val) === 'array' && array_is_list($val)) {
                    foreach ($val as $item) {
                        $options['multipart'][] = $this->serializeMultipartFile($metadata->name, $item);
                    }
                } else {
                    $options['multipart'][] = $this->serializeMultipartFile($metadata->name, $val);
                }
            } elseif ($metadata->json) {
                $serializer = JSON::createSerializer();
                $options['multipart'][] = [
                    'name' => $metadata->name,
                    'headers' => [
                        'Content-Type' => 'application/json',
                    ],
                    'contents' => $serializer->serialize($val, 'json'),
                ];
            } else {
                $dateTimeFormat = $metadata->dateTimeFormat;

                if (gettype($val) === 'array' && array_is_list($val)) {
                    foreach ($val as $item) {
                        $options['multipart'][] = [
                            'name' => $metadata->name,
                            'contents' => valToString($item, ['dateTimeFormat' => $dateTimeFormat]),
                        ];
                    }
                } else {
                    $options['multipart'][] = [
                        'name' => $metadata->name,
                        'contents' => valToString($val, ['dateTimeFormat' => $dateTimeFormat]),
                    ];
                }
            }
        }

        return $options;
    }

    /**
     * @return array<string,mixed>
     */
    private function serializeMultipartFile(string $fieldName, mixed $value): array
    {
        if (gettype($value) !== 'object') {
            throw new \Exception('Invalid type for multipart/form-data file');
        }

        $filename = '';
        $content = '';

        foreach ($value as $field => $val) { /** @phpstan-ignore-line */
            if ($val === null) {
                continue;
            }

            $metadata = $this->parseMultipartMetadata(new ReflectionProperty($value::class, $field));
            if (!$metadata instanceof \Gando\Partner\Utils\MultipartMetadata) {
                continue;
            }
            if (! $metadata->content && ($metadata->name === '' || $metadata->name === '0')) {
                continue;
            }

            if ($metadata->content) {
                $content = $val;
            } else {
                $filename = $val;
            }
        }

        if (empty($filename) || empty($content)) {
            throw new \Exception('Invalid multipart/form-data file');
        }

        return [
            'name' => $fieldName,
            'contents' => $content,
            'filename' => $filename,
        ];
    }

    /**
     * @return array<string,mixed>
     */
    private function serializeFormData(string $fieldName, mixed $value): array
    {
        $options = [
            'form_params' => [],
        ];

        switch (gettype($value)) {
            case 'object':
                foreach ($value as $field => $val) { /** @phpstan-ignore-line */
                    if ($val === null) {
                        continue;
                    }

                    $metadata = $this->parseFormMetadata(new ReflectionProperty($value::class, $field));
                    if (!$metadata instanceof \Gando\Partner\Utils\FormMetadata) {
                        continue;
                    }

                    if ($metadata->json) {
                        $serializer = JSON::createSerializer();
                        $options['form_params'][$metadata->name] = $serializer->serialize($val, 'json');
                    } else {
                        switch ($metadata->style) {
                            case 'form':
                                $values = $this->serializeForm($metadata, $val);
                                foreach ($values as $k => $v) {
                                    $options['form_params'][$k] = $v;
                                }
                                break;
                            default:
                                throw new \Exception("Invalid form style for field $field");
                        }
                    }
                }
                break;
            case 'array':
                if (array_is_list($value)) {
                    throw new \Exception("Invalid request body type for field $fieldName");
                }
                foreach ($value as $k => $v) {
                    $options['form_params'][$k] = valToString($v, []);
                }
                break;
            default:
                throw new \Exception("Invalid request body type for field $fieldName");
        }

        return $options;
    }

    /**
     * @return array<string,mixed>
     */
    private function serializeForm(FormMetadata $metadata, mixed $value): array
    {
        $values = [];

        $dateTimeFormat = $metadata->dateTimeFormat;
        $serializeToString = $metadata->serializeToString;

        switch (gettype($value)) {
            case 'object':
                switch ($value::class) {
                    case \Brick\DateTime\LocalDate::class:
                    case 'DateTime':
                        $values[$metadata->name] = valToString($value, ['dateTimeFormat' => $dateTimeFormat]);
                        break;
                    case \Brick\Math\BigInteger::class:
                    case \Brick\Math\BigDecimal::class:
                        $values[$metadata->name] = valToString($value, ['serializeToString' => $serializeToString]);
                        break;
                    default:
                        if ($value instanceof \BackedEnum) {
                            $values[$metadata->name] = valToString($value, []);
                        } else {
                            $items = [];

                            foreach ($value as $field => $val) { /** @phpstan-ignore-line */
                                if ($val === null) {
                                    continue;
                                }

                                $fieldMetadata = $this->parseFormMetadata(new ReflectionProperty($value::class, $field));
                                if (!$fieldMetadata instanceof \Gando\Partner\Utils\FormMetadata) {
                                    continue;
                                }
                                if ($fieldMetadata->name === '') {
                                    continue;
                                }
                                if ($fieldMetadata->name === '0') {
                                    continue;
                                }

                                if ($metadata->explode) {
                                    $values[$fieldMetadata->name] = valToString($val, ['dateTimeFormat' => $fieldMetadata->dateTimeFormat]);
                                } else {
                                    $items[] = sprintf('%s,%s', $fieldMetadata->name, valToString($val, []));
                                }
                            }

                            if (count($items) > 0) {
                                $values[$metadata->name] = implode(',', $items);
                            }
                        }
                        break;
                }
                break;
            case 'array':
                if (array_is_list($value)) {
                    foreach ($value as $v) {
                        $values[$metadata->name] = valToString($v, ['dateTimeFormat' => $dateTimeFormat]);
                    }
                } else {
                    $items = [];

                    foreach ($value as $k => $v) {
                        if ($metadata->explode) {
                            $values[$k] = valToString($v, ['dateTimeFormat' => $dateTimeFormat]);
                        } else {
                            $items[] = sprintf('%s,%s', $k, valToString($v, ['dateTimeFormat' => $dateTimeFormat]));
                        }
                    }

                    if (count($items) > 0) {
                        $values[$metadata->name] = implode(',', $items);
                    }
                }
                break;
            default:
                $values[$metadata->name] = valToString($value, ['dateTimeFormat' => $dateTimeFormat]);
                break;
        }

        return $values;
    }

    public static function parseRequestMetadata(ReflectionProperty $property): ?RequestMetadata
    {
        $attributes = $property->getAttributes(SpeakeasyMetadata::class);
        if (count($attributes) !== 1) {
            return null;
        }

        $arguments = $attributes[0]->getArguments();
        if (count($arguments) !== 1) {
            return null;
        }

        return RequestMetadata::parse($arguments[0]);
    }

    private function parseMultipartMetadata(ReflectionProperty $property): ?MultipartMetadata
    {
        $metadataStr = SpeakeasyMetadata::find($property->getAttributes(SpeakeasyMetadata::class), 'multipartForm');
        if ($metadataStr === null) {
            return null;
        }

        return MultipartMetadata::parse($metadataStr);
    }

    private function parseFormMetadata(ReflectionProperty $property): ?FormMetadata
    {
        $metadataStr = SpeakeasyMetadata::find($property->getAttributes(SpeakeasyMetadata::class), 'form');
        if ($metadataStr === null) {
            return null;
        }

        return FormMetadata::parse($metadataStr);
    }
}
