<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 71ed88cf4f04
 */

declare(strict_types=1);

namespace Gando\Partner\Utils;

class ServerDetails
{
    /**
     * @param  array<string, string>  $options
     */
    public function __construct(public string $baseUrl, public array $options)
    {
    }
}