<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ced3cce6125c
 */

declare(strict_types=1);

namespace Gando\Partner\Utils\Retry;

class PermanentError extends \Exception
{
}
