<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9492a6123b6f
 */


declare(strict_types=1);

namespace Gando\Partner\Utils\Retry;

class RetryConfigBackoff extends RetryConfig
{
    public RetryStrategy $strategy = RetryStrategy::BACKOFF;

    /**
     * @param int $initialInterval The initial interval in milliseconds.
     * @param int $maxInterval The maximum interval in milliseconds.
     * @param  float  $exponent  The exponent at which the interval grows.
     * @param int $maxElapsedTime The maximum time to keep retrying in milliseconds.
     * @param  bool  $retryConnectionErrors  Whether to retry connection errors.
     */
    public function __construct(public int $initialInterval = 500, public int $maxInterval = 60000, public float $exponent = 1.5, public int $maxElapsedTime = 3600000, public bool $retryConnectionErrors = false)
    {
    }
}
