<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d58c3851b91f
 */

declare(strict_types=1);

namespace Gando\Partner\Utils\Retry;

use Psr\Http\Message\ResponseInterface;

class TemporaryError extends \Exception
{
    public function __construct(string $message = '', int $code = 0, ?\Throwable $previous = null, public ?ResponseInterface $response = null)
    {
        parent::__construct($message, $code, $previous);
    }
}
