<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6fa6ade844c9
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

final readonly class Error
{
    /**
     * @param  ?array<string, mixed>  $details
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Machine-readable error code — exhaustive enum in OpenAPI (`PartnerErrorCode`).
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Components\Code::class)]
        public Code $code,
        /**
         * Human-readable error message.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
        public string $message,
        /**
         * Request correlation ID — include in support tickets.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('requestId')]
        public string $requestId,
        /**
         * Optional structured details.
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('details')]
        #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?array $details = null,
    ) {
    }
}
