<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6a77bdead9b3
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

/** Individual (private) end customer */
enum ParticulierPartnerClientPatchClientType: string
{
    case Particulier = 'particulier';
}
