<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afbd99a7a469
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

/** Business customer; `companyName` is required */
enum ProfessionnelPartnerClientPatchClientType: string
{
    case Professionnel = 'professionnel';
}
