<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9d8cee040798
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

/** ProfessionnelClient - Create a business client. `companyName` is required. */
final readonly class ProfessionnelClient
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Client first name
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
        public string $firstName,
        /**
         * Client last name
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
        public string $lastName,
        /**
         * Client email (unique per account)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
        public string $email,
        /**
         * Business customer; `companyName` is required
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('clientType')]
        #[\Speakeasy\Serializer\Annotation\Type(\Gando\Partner\Models\Components\ProfessionnelClientClientType::class)]
        public ProfessionnelClientClientType $clientType,
        /**
         * Legal or trade name (required for professionnel)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
        public string $companyName,
        /**
         * Target rental operator account id (required on create)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('accountId')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $accountId = null,
        /**
         * Phone number in E.164 or local format
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $phone = null,
        /**
         * French SIREN (9 digits), for business clients
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('siren')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $siren = null,
        /**
         * EU VAT number
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('tvaNumber')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $tvaNumber = null,
        /**
         * Country name or ISO code
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $country = null,
        /**
         * Street address line
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('street')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $street = null,
        /**
         * City
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $city = null,
        /**
         * Postal or ZIP code
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $postalCode = null,
    ) {
    }
}
