<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 673445c57e8d
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

/** Business customer; `companyName` is required */
enum ProfessionnelClientClientType: string
{
    case Professionnel = 'professionnel';
}
