<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c1455a5dbff1
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

/** ProfessionnelPartnerClientPatch - Patch a business client. At least one field is required; `companyName` required when `clientType` is professionnel. */
final readonly class ProfessionnelPartnerClientPatch
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        /**
         * Updated first name
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $firstName = null,
        /**
         * Updated last name
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $lastName = null,
        /**
         * Business customer; `companyName` is required
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('clientType')]
        #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Components\ProfessionnelPartnerClientPatchClientType|null')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?ProfessionnelPartnerClientPatchClientType $clientType = null,
        /**
         * Updated company name (required when setting `clientType` to professionnel)
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $companyName = null,
        /**
         * Updated phone number
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $phone = null,
        /**
         * Updated SIREN
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('siren')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $siren = null,
        /**
         * Updated VAT number
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('tvaNumber')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $tvaNumber = null,
        /**
         * Updated country
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $country = null,
        /**
         * Updated street address
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('street')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $street = null,
        /**
         * Updated city
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $city = null,
        /**
         * Updated postal code
         */
        #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
        #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
        public ?string $postalCode = null,
    ) {
    }
}
