<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7c1ef2c6cbb3
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

use Gando\Partner\Utils\SpeakeasyMetadata;

final readonly class Security
{
    /**
     * @phpstan-pure
     */
    public function __construct(
        #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=x-api-key')]
        public ?string $partnerApiKeyAuth = null,
        #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
        public ?string $partnerBearerAuth = null,
    ) {
    }
}
