<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner;



/** Gando - Gando Partner API v1: API for **rental management software** and **multi–rental-operator platforms** integrating Gando on behalf of linked rental operators. Use **`gando_pk_`** keys (`x-api-key` or `Authorization: Bearer`) on `/api/partner/v1/*`. */
class Gando
{
    public const SERVERS = [
        'http://localhost:3000',
    ];

    /**
     * Rental operator account management — list linked accounts and revoke partner links.
     *
     * @var Accounts $$accounts
     */
    public Accounts $accounts;

    /**
     * Client management endpoints — create, list, retrieve and update clients.
     *
     * @var Clients $$clients
     */
    public Clients $clients;

    /**
     * ## Gando Partner API v1
     *
     *
     * Routes under `/api/partner/v1/*` use **partner API keys** only (`gando_pk_` prefix).
     *
     * ### Authentication
     *
     * - Send the raw key in either:
     *   - Header **`x-api-key: gando_pk_…`**, or
     *   - Header **`Authorization: Bearer gando_pk_…`**
     * - Missing key or wrong prefix → **401** `error.code`: **`missing_api_key`**.
     * - Unknown key → **401** `error.code`: **`invalid_api_key`**.
     * - Revoked key → **401** `error.code`: **`api_key_revoked`**.
     *
     * ### Error responses (ErrorEnvelope)
     *
     * All documented 4xx/5xx responses use the same JSON shape (`#/components/schemas/ErrorEnvelope`):
     *
     * ```json
     * {
     *   "error": {
     *     "code": "invalid_request",
     *     "message": "Human-readable error message.",
     *     "requestId": "req_abc123"
     *   }
     * }
     * ```
     *
     * ### Idempotency-Key (mutating POST)
     *
     * Optional header on **`POST /api/partner/v1/deposits`**, **`POST /api/partner/v1/clients`**, **`POST /api/partner/v1/deposits/{id}/capture`**, and **`POST /api/partner/v1/deposits/{id}/cancel`**. Send a **UUID v4** per logical operation. Within **24 hours**, repeating the same key with the **same JSON body** returns the **cached HTTP status and response**. Reusing the key with a **different body** returns **409** with `error.code`: `idempotency_key_conflict`.
     *
     * ### curl (partner key)
     *
     * ```bash
     * curl -sS -X GET "https://gando.app/api/partner/v1/deposits?page=1&limit=20" \
     *   -H "x-api-key: gando_pk_YOUR_PARTNER_KEY"
     * ```
     *
     * ### Migration from `/api/partner/*`
     *
     * Legacy routes at `/api/partner/*` return `Deprecation: true` and `Sunset` headers pointing to this v1 API. Migrate before the sunset date to avoid 410 Gone responses.
     *
     * @var Deposits $$deposits
     */
    public Deposits $deposits;

    /**
     * ## Partner webhooks (v1)
     *
     *
     * Register **HTTPS endpoints** that receive JSON events for your entire partner integration (same `gando_pk_` authentication as `/api/partner/v1/*`). Use this instead of polling **`GET /api/partner/v1/accounts`** when you need the Gando **`accountId`** as soon as a rental operator completes partner connect.
     *
     * ### Authentication
     *
     * Send your partner API key with **`x-api-key: gando_pk_…`** or **`Authorization: Bearer gando_pk_…`** (same as other v1 routes).
     *
     * ### Events
     *
     * - **`rental_operator.linked`** — Fired when a rental operator account is linked to your partner via connect. Payload includes Gando `accountId`, your `externalId` from the connect URL, and `partnerId`.
     * - **`deposit.status_changed`** — Wildcard. Delivered for every deposit status transition (same JSON shape as `#/components/schemas/WebhookDepositStatusChangedEvent`), including optional `data.partnerContext` when the deposit belongs to a linked rental operator.
     * - **`deposit.activated`** — Delivered only when a deposit transitions to `active`.
     * - **`deposit.captured`** — Delivered only when a deposit transitions to `captured`.
     * - **`deposit.expired`** — Delivered only when a deposit transitions to `close` (natural end of contract).
     * - **`deposit.cancelled`** — Delivered only when a deposit transitions to `cancelled` (manual cancellation).
     *
     * When a subscription includes both the wildcard and a specific event, **the most specific subscribed event wins** for that transition (single delivery per endpoint). The `event` field of the payload reflects the chosen event so consumers can branch on it directly.
     *
     * ### Signing and headers
     *
     * **`X-Gando-Signature`** (`sha256=<hex>`), **`X-Gando-Timestamp`** (unix seconds), **`X-Gando-Event`** (event name). Verify HMAC-SHA256 over `<timestamp>.<rawBody>` with your **webhook signing secret** (returned once when you create the endpoint). See the **Webhooks** tag for full verification examples (Node.js, Python, PHP, Go).
     *
     * ### Retries
     *
     * Failed deliveries are retried on a backoff schedule by Gando's webhook retry job.
     *
     * @var Webhooks $$webhooks
     */
    public Webhooks $webhooks;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return GandoBuilder
     */
    public static function builder(): GandoBuilder
    {
        return new GandoBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->accounts = new Accounts($this->sdkConfiguration);
        $this->clients = new Clients($this->sdkConfiguration);
        $this->deposits = new Deposits($this->sdkConfiguration);
        $this->webhooks = new Webhooks($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}